"""add saves and watch time to analytics

Revision ID: 778be997854d
Revises: 54762ca0329d
Create Date: 2026-09-09 12:29:35.621230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778be997854d'
down_revision: Union[str, Sequence[str], None] = '54762ca0329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('analytics', sa.Column('watch_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'watch_time')
    op.drop_column('analytics', 'saves')
    # ### end Alembic commands ###
